// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proptimo.Persistence.Context;

#nullable disable

namespace Proptimo.Persistence.Migrations
{
    [DbContext(typeof(ProptimoDbContext))]
    [Migration("20250805090615_mig-3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proptimo.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstate", b =>
                {
                    b.Property<string>("RealEstateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RealEstateTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RealEstateId");

                    b.HasIndex("RealEstateTypeId");

                    b.ToTable("RealEstates");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateAddress", b =>
                {
                    b.Property<string>("RealEstateAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NeighborhoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateAddressId");

                    b.ToTable("RealEstateAddresses");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateImage", b =>
                {
                    b.Property<string>("RealEstateImageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RealEstateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RealEstateImageId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("RealEstateImages");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateType", b =>
                {
                    b.Property<string>("RealEstateTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateTypeId");

                    b.ToTable("RealEstateTypes");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateTypeFeature", b =>
                {
                    b.Property<string>("RealEstateTypeFeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealEstateTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RealEstateTypeFeatureId");

                    b.HasIndex("RealEstateTypeId");

                    b.ToTable("RealEstateTypeFeatures");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateTypeFeatureValue", b =>
                {
                    b.Property<string>("RealEstateTypeFeatureValueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RealEstateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RealEstateTypeFeatureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealEstateTypeFeatureValueId");

                    b.HasIndex("RealEstateId");

                    b.HasIndex("RealEstateTypeFeatureId");

                    b.ToTable("realEstateTypeFeatureValues");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstate", b =>
                {
                    b.HasOne("Proptimo.Domain.Entities.RealEstateType", "RealEstateType")
                        .WithMany("RealEstates")
                        .HasForeignKey("RealEstateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateType");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateImage", b =>
                {
                    b.HasOne("Proptimo.Domain.Entities.RealEstate", "RealEstate")
                        .WithMany("Images")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateTypeFeature", b =>
                {
                    b.HasOne("Proptimo.Domain.Entities.RealEstateType", "RealEstateType")
                        .WithMany("RealEstateTypeFeatures")
                        .HasForeignKey("RealEstateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateType");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateTypeFeatureValue", b =>
                {
                    b.HasOne("Proptimo.Domain.Entities.RealEstate", "RealEstate")
                        .WithMany("FeatureValues")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proptimo.Domain.Entities.RealEstateTypeFeature", "RealEstateTypeFeature")
                        .WithMany()
                        .HasForeignKey("RealEstateTypeFeatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RealEstate");

                    b.Navigation("RealEstateTypeFeature");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstate", b =>
                {
                    b.Navigation("FeatureValues");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Proptimo.Domain.Entities.RealEstateType", b =>
                {
                    b.Navigation("RealEstateTypeFeatures");

                    b.Navigation("RealEstates");
                });
#pragma warning restore 612, 618
        }
    }
}
